name: Build and Upload ZIP

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  zip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'

      - name: Install dependencies
        run: yarn

      - name: Build ZIP
        run: yarn zip

      - name: Upload ZIP Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ChangeNarrator
          path: .output/*.zip
          include-hidden-files: true
